### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by DataHippo93** [AdamRisberg/react-image-magnifiers#1]
First of all this package is GREAT. I searched far and wide for image viewer with the magnifier functionality and I wanted and finally found exactly what I wanted here.

How can I put this inside a modal pop up?

**Comment by AdamRisberg** [comment]
Thanks! I'm glad this project was helpful for you.

I'm not sure how to answer your question yet. What issue did you have when you tried putting it into a modal? I just tried it and it worked with just the default props for me.

**Comment by AdamRisberg** [comment]
I haven't gotten a response about this and it doesn't seem like there is anything that needs fixing, so I'm closing this issue.
