### ISSUE TITLE
Is there an event triggered when the zoom starts?

### ISSUE THREAD

**Issue by mihai-rebag** [AdamRisberg/react-image-magnifiers#12]
Hello! Nice plugin, thanks a lot for prompt updates.
Is there a way to know when the zoom event starts? Couldn't find anything.
I need to execute some functions when the zoom event starts and again when it ends (I'm using double click and tap)

**Comment by AdamRisberg** [comment]
Sorry it took me so long to respond. I'm looking into adding this feature today and I'll let you know when it's finished.

**Comment by AdamRisberg** [comment]
This feature is now available in the newest version (1.2.3). In this version, you can pass callbacks to the "onZoomStart" and "onZoomEnd" props of any magnifier component.

**Comment by mihai-rebag** [comment]
Works excellent! Thanks a lot!
