### ISSUE TITLE
Is this library compatible with base64 image?

### ISSUE THREAD

**Issue by weslei-dias-vakt** [AdamRisberg/react-image-magnifiers#14]
I'm trying to use this library in my base64 images, but when i hover the image i only have an grey square instead of a zoom.
This is my code 
`<Magnifier src={`data:image/png;base64,${page.images[0]}`} mgShape="square" />`

Any ideas?

**Comment by etomarat** [comment]
@weslei-dias-vakt hi! did you solve the issue? I tried to use "BLOB" and "Base 64", but there is no effect.

**Comment by weslei-dias-vakt** [comment]
Hey @etomarat,
Yes.
To fix the issue i did following workaround.

```
    const image = new Image();
    image.src = `data:image/jpeg;base64,${item}`;
    image.src = image.src.replace(/(\r\n|\n|\r)/gm, '');
```

**Comment by etomarat** [comment]
@weslei-dias-vakt thank you! Can you tell me what "item" means? and what should be passed to Magnifier "imageSrc"?

**Comment by weslei-dias-vakt** [comment]
item is the base64 hash of the image. on the imageSrc you should pass like src={image.src}

**Comment by etomarat** [comment]
It does not work for me :( magnifier has no src anyway. Thanks for your help!

**Comment by weslei-dias-vakt** [comment]
Can be the version.
This is my component

```
import React from 'react';
import Magnifier from 'react-magnifier';
import { Fade } from 'react-slideshow-image';

// eslint-disable-next-line react/prop-types
const ImageRender = ({ images }) => {
  const generatedImages = images?.map(item => {
    const image = new Image();
    image.src = `data:image/jpeg;base64,${item}`;
    image.src.replace(/(\r\n|\n|\r)/gm, '');
    return image;
  });

  const properties = {
    duration: 500000,
    transitionDuration: 500,
    infinite: false,
    indicators: false,
    defaultIndex: 0,
    autoplay: false
  };

  return (
    <Fade {...properties}>
      {
          generatedImages?.map((image, index) => {
            return (
              <div data-testid="extracted-image" key={index}>
                <Magnifier src={image.src} mgShape="square" />
                <span className="indicator-page">Page {index + 1}</span>
              </div>
            );
          })
      }
    </Fade>
  );
};

export default ImageRender;
```
This is my version "react-magnifier": "^3.0.4",

**Comment by etomarat** [comment]
Looks like you a using another package. This package has name "react-image-magnifiers": "^1.4.0". I will try `react-magnifier`now, thanx

**Comment by weslei-dias-vakt** [comment]
yes, in the end they do the same thing
