### ISSUE TITLE
Custom white box (representing the zoom area)

### ISSUE THREAD

**Issue by arso1er** [AdamRisberg/react-image-magnifiers#17]
Hi,
I'd like to know if I can customize the white box (representing the zoom area) within the small preview image.
Thanks.

**Comment by AdamRisberg** [comment]
Right now the only customization available is changing the opacity of that box. However, I can probably add in some more options in the next update. What were you looking to customize on it?

**Comment by arso1er** [comment]
I wanted something like amazon: a div with a background image instead of the white box.

**Comment by AdamRisberg** [comment]
Yeah, I should be able to add that feature into the next update. Should be done within the next day or two. I've got a couple of other things I want to include.

**Comment by arso1er** [comment]
OK. Thanks. If you could look at my previous issue too, It would be great.

**Comment by AdamRisberg** [comment]
It wouldn't feel right to only notify you on one issue. :) So, I just published the update to NPM (version 1.3.0). You can now give the preview box a background image on all applicable components. The overlay color and box border color can also be changed now. So, if you only want to use a background image, you can set the overlayOpacity to zero and set the overlayBoxColor to transparent.

**Comment by arso1er** [comment]
After update, I got exactly what I wanted.

Thanks again.
