### ISSUE TITLE
Feature Request: Interaction hint

### ISSUE THREAD

**Issue by tpinne** [AdamRisberg/react-image-magnifiers#2]
Hi, 

great library and more up-to-date than some other components regarding current react depracations. In another library though, there is little nice feature "interaction hint" which adds nice UX for users to see that there is interaction possibility without accidentally hovering the image. https://ethanselzer.github.io/react-image-magnify/#/hint

Would be great to see something similar in this library :-)

**Comment by AdamRisberg** [comment]
Thanks! I will keep this in mind for the next release. In the meantime, if you need a solution now, all of the magnifier components have a renderOverlay render prop that could be used for this purpose. Here's an example:

`<Magnifier
     imageSrc="./image.jpg"
     renderOverlay={active =>
          !active && <InteractionHint>Click to zoom</InteractionHint>
     }
/>`

No default styling is provided for the render prop content, so in the above example, the InteractionHint component would need absolute position and a z-index of 1 or higher.

**Comment by tpinne** [comment]
Sounds like a reasonable solution. Thanks 👍🏻
