### ISSUE TITLE
Question: Way to change zoom level?

### ISSUE THREAD

**Issue by ChrisEddy** [AdamRisberg/react-image-magnifiers#20]
I want to change the amount of zoom.

Is there a way to do this now? 

I think it would be useful to have this feature as some use cases want more intense zoom then what is default.

**Comment by AdamRisberg** [comment]
To avoid quality loss on zoom, the components aren't actually using a digital zoom that can be controlled through code. The level of zoom is governed by the rendered size difference between the small and large versions of the image. In other words, providing a larger (higher resolution) image will increase the zoom effect. Double the resolution of the image being passed to "largeImageSrc" (or "imageSrc" if only using one) and it doubles the amount of zoom.

**Comment by ChrisEddy** [comment]
Ohhhh I see. Thank you for the clarification on how zooming works, I thought it was digital zoom.
