### ISSUE TITLE
Images with transparency are visually overlaping

### ISSUE THREAD

**Issue by rafw87** [AdamRisberg/react-image-magnifiers#22]
When `Magnifier` image has transparent background (for example SVG) then both images are visible and overlapped when zoomed.
Hiding "main image" in `MagnifierRenderer.js` seems to be enough to fix this problem:
```js
visibility: isActive ? "hidden" : "visible"
```

**Comment by AdamRisberg** [comment]
I'll add this in to the next update, after looking into your other issue.

**Comment by AdamRisberg** [comment]
I just posted version 1.3.2 with this fix.
