### ISSUE TITLE
Image Mask

### ISSUE THREAD

**Issue by Dadatata-JZ** [AdamRisberg/react-image-magnifiers#24]
Hi dear, 

I am trying to implement this lib for displaying images matrix. I am looking for some neat solutions to use CSS mask my input images and then apply glass magnifier only on the masked (display) part of the image.

Any suggestions? 

Thanks

**Comment by AdamRisberg** [comment]
I'm not sure what you mean by "images matrix". Is it like a sprite sheet where you want to crop down to only display a small square of a larger image?

**Comment by Dadatata-JZ** [comment]
Yea. I am basically trying to visualize a m by n array of images.
