### ISSUE TITLE
Can't change activation method in side-by-side magnifier

### ISSUE THREAD

**Issue by Volizik** [AdamRisberg/react-image-magnifiers#26]
Hi! Thanks for your work! I have some issue. Why I can change activation method only in Magnifier? I need activation on double tap in mobile (like in Magnifier) and hovre in desctop (like in SideBySideMagnifier). There is hardcode value.

**Comment by AdamRisberg** [comment]
Sorry for the late response. The SideBySideMagnifier does provide mouseActivation and touchActivation props. The options are provided in named export constants (TOUCH_ACTIVATION and MOUSE_ACTIVATION).
