### ISSUE TITLE
FEATURE: Make SideBySideRenderer SSR compatible

### ISSUE THREAD

**Issue by tpinne** [AdamRisberg/react-image-magnifiers#3]
Because of the use of `window` in https://github.com/AdamRisberg/react-image-magnifiers/blob/476bba1958e75fcf14f4f966928c1ee07e6be373/src/SideBySideRenderer.js#L28 the component is not SSR compatible throwing a reference error that `window` is not defined, obviously.

Don't know about the performance impact, but maybe it's possible to render the large preview container only `onMouseEnter` and calculate whether to use `inPlace` or not at that moment.

Maybe it's even enough to add the `active` variable to the check in line 28 because this should never be true during SSR.

**Comment by AdamRisberg** [comment]
It should be fixed now. If window doesn't exist, the expression will evaluate to false without trying to access innerWidth. I just published the fix to npm (version 1.0.5).

**Comment by AdamRisberg** [comment]
After some testing, I realized that this issue still existed. As of version 1.0.7, it is now fully fixed and all components support SSR.
