### ISSUE TITLE
image dimension

### ISSUE THREAD

**Issue by mbgame** [AdamRisberg/react-image-magnifiers#4]
hi adam

**Comment by mbgame** [comment]
when i use the lib i get this warning too about passive event
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event

can u fix that too or any advice?

**Comment by AdamRisberg** [comment]
I just published a fix to NPM (version 1.0.6) that should fix those non-passive event warnings. The update should also help avoid the size issues you mentioned before by minimizing the chance of CSS affecting certain elements within the components.

**Comment by mbgame** [comment]
thx adam,
I checked that the problem was fixed.
