### ISSUE TITLE
onError function

### ISSUE THREAD

**Issue by ozanoz34** [AdamRisberg/react-image-magnifiers#9]
Is there a way to use onError function for the <img> tag? Because right now as I see, when the original src link doesn't work, there is no fallBackUrl option.

**Comment by AdamRisberg** [comment]
I added an image fallback feature (version 1.2.1). The imageSrc and largeImageSrc props on all components now accept either a single image path or an array of paths. If an array is provided, it will try each path in order until either one loads, or the end of the array is reached.

**Comment by ozanoz34** [comment]
Thank you for the quick answer and quick fix! Everything works fine now :)
